syntax = "proto3";

package family;

option java_multiple_files = true;
option java_package = "com.example.family";
option java_outer_classname = "FamilyProto";

service FamilyService {
  rpc joinFamily (JoinRequest) returns (JoinResponse);
  rpc store (StoredMessage) returns (StoreResult);
  // YENİ EKLENEN: Veri okuma isteği
  rpc getValue (GetValueRequest) returns (GetValueResponse);
}

message JoinRequest {
  string host = 1;
  int32 port = 2;
}

message JoinResponse {
  bool success = 1;
  string message = 2;
}

message StoredMessage {
  int32 id = 1;
  string data = 2;
}

message StoreResult {
  bool success = 1;
  string message = 2;
}

// YENİ MESAJ TİPLERİ
message GetValueRequest {
  int32 id = 1;
}

message GetValueResponse {
  bool found = 1;
  string data = 2;
}